namespace FreightTracker.API.Models;

// The fixed set of states a shipment can be in.
// Backed by int (Pending = 0, InTransit = 1, ...) but we'll store it as text.
public enum ShipmentStatus
{
    Pending,
    InTransit,
    Delivered,
    Cancelled
}

// The entity: one instance = one row in the Shipments table.
public class Shipment
{
    public int Id { get; set; }                       // primary key, auto-generated by the DB
    public string TrackingNumber { get; set; } = "";  // unique, server-generated
    public string Origin { get; set; } = "";
    public string Destination { get; set; } = "";
    public string Carrier { get; set; } = "";
    public decimal WeightKg { get; set; }
    public ShipmentStatus Status { get; set; } = ShipmentStatus.Pending;
    public DateTime? EstimatedDelivery { get; set; }  // nullable — the '?' means optional
    public DateTime CreatedAt { get; set; }
}
